

CREATE TABLE TBL_USER
(
 USERID			INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,FIRST_NAME		VARCHAR(50) NOT NULL
,LAST_NAME		VARCHAR(50)
,DOB			 DATETIME
,MOBILE1		BIGINT NOT NULL
,MOBILE2		BIGINT 
,EMAIL			VARCHAR(50)
,GENDER			VARCHAR(10)
,USERNAME		VARCHAR(50) NOT NULL
,USER_PASSWORD	VARCHAR(50) NOT NULL
,ROLE_ID		INT FOREIGN KEY REFERENCES TBL_ROLE(ROLE_ID) NOT NULL
,ADDRESS_ID		INT FOREIGN KEY REFERENCES TBL_ADDRESS(ADDRESS_ID) NOT NULL
,CREATED_BY		INT NOT NULL
,CREATED_DATE	DATETIME NOT NULL
,MODIFIED_BY	INT
,MODIFIED_DATE	DATETIME
,IS_ACTIVE		BIT 
,IS_DELETE		BIT
)

CREATE TABLE TBL_ROLE
(
 ROLE_ID		INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,ROLE_NAME		VARCHAR(30)
,CREATED_BY		INT NOT NULL
,CREATED_DATE	DATETIME NOT NULL
,MODIFIED_BY	INT
,MODIFIED_DATE	DATETIME
,IS_ACTIVE		BIT 
)

CREATE TABLE TBL_ADDRESS
(
 ADDRESS_ID				INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,PERMANET_ADDRESS		VARCHAR(500)
,TEMPRORARY_ADDRESS		VARCHAR(500)
,COUNTRY_ID				INT FOREIGN KEY REFERENCES TBL_COUNTRY_MASTER(COUNTRY_ID) NOT NULL
,STATE_ID				INT FOREIGN KEY REFERENCES TBL_STATE_MASTER(STATE_ID) NOT NULL
,DISTRICT_ID			INT FOREIGN KEY REFERENCES TBL_DISTRICT_MASTER(DISTRICT_ID) NOT NULL
,CITY_ID				INT FOREIGN KEY REFERENCES TBL_CITY_MASTER(CITY_ID) NOT NULL
,AREA_ID				INT FOREIGN KEY REFERENCES TBL_AREA_MASTER(AREA_ID) NOT NULL
,PINCODE				BIGINT
,CREATED_BY				INT NOT NULL
,CREATED_DATE			DATETIME NOT NULL
,MODIFIED_BY			INT
,MODIFIED_DATE			DATETIME
,IS_ACTIVE				BIT 
,IS_DELETE				BIT
)

CREATE TABLE TBL_COUNTRY_MASTER 
(
    COUNTRY_ID		INT IDENTITY(1,1) PRIMARY KEY NOT NULL
    ,COUNTRY_NAME	VARCHAR(100) NOT NULL
	,CREATED_BY		INT NOT NULL
	,CREATED_DATE	DATETIME NOT NULL
	,MODIFIED_BY	INT
	,MODIFIED_DATE	DATETIME
	,IS_ACTIVE		BIT
)

CREATE TABLE TBL_STATE_MASTER 
(
     STATE_ID		INT IDENTITY(1,1) PRIMARY KEY NOT NULL
    ,STATE_NAME		VARCHAR(100) NOT NULL
	,CREATED_BY		INT NOT NULL
	,CREATED_DATE	DATETIME NOT NULL
	,MODIFIED_BY	INT
	,MODIFIED_DATE	DATETIME
	,IS_ACTIVE		BIT
    ,COUNTRY_ID		INT	FOREIGN KEY REFERENCES TBL_COUNTRY_MASTER(COUNTRY_ID)
)

CREATE TABLE TBL_DISTRICT_MASTER 
(
     DISTRICT_ID	INT IDENTITY(1,1) PRIMARY KEY NOT NULL
    ,DISTRICT_NAME  VARCHAR(100) NOT NULL
	,CREATED_BY		INT NOT NULL
	,CREATED_DATE	DATETIME NOT NULL
	,MODIFIED_BY	INT
	,MODIFIED_DATE	DATETIME
	,IS_ACTIVE		BIT
    ,STATE_ID       INT FOREIGN KEY REFERENCES TBL_STATE_MASTER(STATE_ID)
)

CREATE TABLE TBL_CITY_MASTER 
(
     CITY_ID		INT IDENTITY(1,1) PRIMARY KEY NOT NULL
    ,CITY_NAME		VARCHAR(100) NOT NULL
	,CREATED_BY		INT NOT NULL
	,CREATED_DATE	DATETIME NOT NULL
	,MODIFIED_BY	INT
	,MODIFIED_DATE	DATETIME
	,IS_ACTIVE		BIT
    ,DISTRICT_ID	INT FOREIGN KEY REFERENCES TBL_DISTRICT_MASTER(DISTRICT_ID)
)

CREATE TABLE TBL_AREA_MASTER 
(
     AREA_ID		INT IDENTITY(1,1) PRIMARY KEY NOT NULL
    ,AREA_NAME		VARCHAR(100) NOT NULL
	,CREATED_BY		INT NOT NULL
	,CREATED_DATE	DATETIME NOT NULL
	,MODIFIED_BY	INT
	,MODIFIED_DATE	DATETIME
	,IS_ACTIVE		BIT
    ,CITY_ID		INT FOREIGN KEY REFERENCES TBL_CITY_MASTER(CITY_ID)
)

CREATE TABLE TBL_RELIGION_MASTER
(
  RELIGION		 INT IDENTITY(1,1) PRIMARY KEY NOT NULL
 ,RELIGION_NAME  VARCHAR(30)
 ,CREATED_BY	 INT NOT NULL
 ,CREATED_DATE	 DATETIME NOT NULL
 ,MODIFIED_BY	 INT
 ,MODIFIED_DATE	 DATETIME
 ,IS_ACTIVE		 BIT
)

CREATE TABLE TBL_STUDENT
(
  STUDENT_ID	  INT IDENTITY(1,1) PRIMARY KEY NOT NULL
 ,USERID		  INT FOREIGN KEY REFERENCES TBL_USER(USERID) 
 ,STUDENT_REG_NO  VARCHAR(20)
 ,STUDENT_NAME	  VARCHAR(50)
 ,GENDER		  VARCHAR(10)
 ,DOB			  DATETIME
 ,CREATED_BY	  INT NOT NULL
 ,CREATED_DATE	  DATETIME NOT NULL
 ,MODIFIED_BY	  INT
 ,MODIFIED_DATE	  DATETIME
 ,IS_ACTIVE		  BIT
 ,IS_DELETE		  BIT
)

CREATE TABLE TBL_STUDENT_DETAIL
(
 STUDENT_DETAIL_ID			     INT IDENTITY(1,1) PRIMARY KEY  NOT NULL
 ,STUDENT_ID					 INT FOREIGN KEY REFERENCES TBL_STUDENT(STUDENT_ID)
-- ,USERID						 INT FOREIGN KEY REFERENCES TBL_USER(USERID) 
 ,PROFILE_PIC					 VARCHAR(50)
 ,BLOOD_GROUP					 VARCHAR(5)
 ,PARENT_OR_GUARDIAN_OCCUPATION  VARCHAR(50)
 ,CREATED_BY					 INT NOT NULL
 ,CREATED_DATE					 DATETIME NOT NULL
 ,MODIFIED_BY					 INT
 ,MODIFIED_DATE					 DATETIME

)
                                                  
CREATE TABLE TBL_STUDENT_PREVIOUS_SCHOOL_DETAIL
(                                                                                                   
 STUDENT_PREVIOUS_SCHOOL_DETAIL_ID  INT IDENTITY(1,1) PRIMARY KEY  NOT NULL
,SCHOOL_NAME						VARCHAR(500)
,SCHOOL_ADDRESS						VARCHAR(500)
,MEDIUM_OF_INSTRUCTION				VARCHAR(50)
,FROM_STUDIED						VARCHAR(50)
,TO_STUDIED							VARCHAR(50)
,LAST_SCHOOL_RESULT					VARCHAR(20)
,REASON_FOR_LEAVING					VARCHAR(20)
,GUARDIAN_FIRST_NAME				VARCHAR(30)
,GUARDIAN_LAST_NAME					VARCHAR(30)
,GUARDIAN_EMAIL						VARCHAR(30)
,GUARDIAN_MOBILE					BIGINT
,GUARDIAN_OCCUPATION				VARCHAR(50)
,ATTACHED_TC						VARCHAR(50)
,ATACHED_REPORT_CARD				VARCHAR(50)
)

CREATE TABLE TBL_ADDMISSION_REGISTRATION
(
  ADDMISSION_REGISTRATION_ID INT IDENTITY(1,1) PRIMARY KEY  NOT NULL
 ,ADDMISSION_NUMBER			 VARCHAR(50)
 ,STUDENT_NAME			     VARCHAR(50)
 ,GENDER				     VARCHAR(10)
 ,DOB					     DATETIME
 ,PARENTS_FIRST_NAME         VARCHAR(50)
 ,PARENTS_LAST_NAME			 VARCHAR(50)
 ,PERMANET_ADDRESS			 VARCHAR(500)
 ,TEMPRORARY_ADDRESS		 VARCHAR(500)
 ,RELIGION_ID				 INT
 ,NATIONALITY				 VARCHAR(30)
 --,USERID				     INT FOREIGN KEY REFERENCES TBL_USER(USERID) 
 ,CREATED_BY			     INT NOT NULL
 ,CREATED_DATE			     DATETIME NOT NULL
 ,MODIFIED_BY			     INT
 ,MODIFIED_DATE			     DATETIME
 ,IS_APPROVAL				 BIT
 ,IS_ADMITTED				 BIT
 )